server:
  port: 8081

spring:
  application:
    name: customer-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:6534/rigdb
    username: postgres
    password: postgres
    maximum-pool-size: 3
    minimum-idle: 3

grpc:
  client:
    discount-calculator:
      address: 'static://127.0.0.1:8012'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

kafka:
  topic:
    order: order
  address: localhost:9092

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

scheduler:
  enabled: ${SCHEDULER_ENABLED:true}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"