server:
  port: 8083

spring:
  application:
    name: order-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:6534/rigdb
    username: postgres
    password: postgres
    maximum-pool-size: 3
    minimum-idle: 3
  kafka:
    consumer:
      max-poll-records: 1

kafka:
  groupId: order
  topic:
    order: order
  address: localhost:9092

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans" # spring boot 3 de uzak sunucu adresini boyle ekliyoruz

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
